'use client';
import { useState } from 'react';
import { ChevronDown, MessageSquare, Mail, Phone, Zap, Search, ExternalLink } from 'lucide-react';
import { BRAND } from '@/lib/brand';
import clsx from 'clsx';

const SECTIONS = [
  {
    title: 'Understanding your dashboard',
    icon: '📊',
    faqs: [
      {
        q: 'What is the ClarityScore™?',
        a: `The ClarityScore™ is a live 0–1000 number that summarises how your brand is performing across all connected platforms. It weighs follower growth, engagement rates, content consistency, audience quality, and competitive position. Higher is better. Think of it as your brand's health check — updated daily by ${BRAND.aria}.`,
      },
      {
        q: 'How often is my data updated?',
        a: 'Your data syncs automatically from connected platforms every hour. Reports generated by Cerebre are updated as soon as they are uploaded, usually within 24 hours of submission.',
      },
      {
        q: `What does 'Ask ${BRAND.aria}' do?`,
        a: `${BRAND.aria} (${BRAND.ariaFull}) is an AI analyst that has read all your brand data. You can ask it anything in plain English — "Why did my engagement drop last week?", "What should we post for Christmas?", "How do we compare to our competitors?" — and it answers using your actual numbers.`,
      },
      {
        q: 'Where does the competitor data come from?',
        a: 'Cerebre monitors your competitors\' public social profiles daily. This data is aggregated and anonymised — the DepthView™ feature shows you where you stand relative to them without exposing any private information.',
      },
    ],
  },
  {
    title: 'Goals and tracking',
    icon: '🎯',
    faqs: [
      {
        q: 'What is the VelocityTracker™?',
        a: `VelocityTracker™ shows whether you're accelerating toward your goals or falling behind. It projects your current growth rate forward and compares it to your targets. If you're "ahead", you're growing faster than needed to hit the target. If "behind", Cerebre knows to push harder.`,
      },
      {
        q: 'Can I suggest a new goal?',
        a: 'Yes — speak to your Cerebre account manager and they will add it to your brand dashboard. Goals can be set for any metric: followers, website visits, engagement rate, sales leads, and more.',
      },
    ],
  },
  {
    title: 'Your Cerebre team',
    icon: '👥',
    faqs: [
      {
        q: 'How do I rate my team?',
        a: 'Go to the Team section in your portal. You can rate each staff member monthly on communication, quality of work, responsiveness, and strategic value. Ratings are private — only the team member and Cerebre leadership can see them.',
      },
      {
        q: 'What is the Proof of Value report?',
        a: `Every month, ${BRAND.aria} automatically generates a Proof of Value report — a clear evidence document showing exactly what Cerebre did for your brand, which metrics moved, and how those movements correlate to the work done. It's designed to answer the question: "What are we actually getting for our investment?"`,
      },
      {
        q: 'What are "Strategies" in my portal?',
        a: 'Strategies are plans your Cerebre team has written and submitted for your brand — content strategy, campaign plans, growth roadmaps. Each one goes through AI validation before you see it. You can view the full strategy, its validation score, and its results once executed.',
      },
    ],
  },
  {
    title: 'Account and security',
    icon: '🔒',
    faqs: [
      {
        q: 'How do I change my password?',
        a: 'Go to Settings → Security in the left navigation. Enter your current password and choose a new one. If you have forgotten your password, use the "Forgot password" link on the login screen.',
      },
      {
        q: 'Can I add another person from my team?',
        a: 'Yes — contact your Cerebre account manager and they can create an additional portal user for your organisation. Each user has their own login.',
      },
      {
        q: 'Is my brand data secure?',
        a: 'Yes. Your data is encrypted at rest and in transit. Only your assigned Cerebre team members and leadership can view your brand metrics. Competitor data shown in your portal is processed and anonymised before display.',
      },
    ],
  },
];

const Faq = ({ q, a }: { q: string; a: string }) => {
  const [open, setOpen] = useState(false);
  return (
    <div className="border-b" style={{ borderColor: 'rgba(255,255,255,0.06)' }}>
      <button onClick={() => setOpen(o => !o)}
        className="w-full flex items-start justify-between gap-4 py-4 text-left text-sm font-semibold text-white/75 hover:text-white transition-colors">
        <span>{q}</span>
        <ChevronDown className={clsx('w-4 h-4 flex-shrink-0 mt-0.5 text-purple-400 transition-transform duration-200', open && 'rotate-180')} />
      </button>
      {open && (
        <div className="pb-4 text-sm leading-relaxed" style={{ color: 'rgba(255,255,255,0.5)' }}>{a}</div>
      )}
    </div>
  );
};

export default function ClientHelpPage() {
  const [search, setSearch] = useState('');

  const filtered = SECTIONS.map(s => ({
    ...s,
    faqs: s.faqs.filter(f => !search || f.q.toLowerCase().includes(search.toLowerCase()) || f.a.toLowerCase().includes(search.toLowerCase())),
  })).filter(s => s.faqs.length > 0);

  return (
    <div className="p-6 lg:p-8 max-w-3xl">
      <div className="mb-8">
        <div className="flex items-center gap-2 mb-1">
          <div className="w-1 h-5 rounded-full" style={{ background: '#6d28d9' }} />
          <p className="text-xs font-bold text-purple-400 uppercase tracking-widest">Support</p>
        </div>
        <h1 className="text-2xl font-black text-white">Help Centre</h1>
        <p className="text-white/40 text-sm mt-1">Everything you need to get the most from {BRAND.name}</p>
      </div>

      {/* Search */}
      <div className="relative mb-8">
        <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-white/25" />
        <input
          value={search} onChange={e => setSearch(e.target.value)}
          placeholder="Search help articles…"
          className="w-full rounded-xl pl-11 pr-4 py-3.5 text-sm text-white placeholder-white/20 outline-none focus:ring-2 focus:ring-purple-500/50 transition-all"
          style={{ background: 'rgba(255,255,255,0.06)', border: '1px solid rgba(255,255,255,0.1)' }}
        />
      </div>

      {/* FAQ sections */}
      <div className="space-y-6">
        {filtered.map(section => (
          <div key={section.title} className="rounded-2xl border overflow-hidden" style={{ background: 'rgba(255,255,255,0.03)', borderColor: 'rgba(255,255,255,0.08)' }}>
            <div className="flex items-center gap-3 px-5 py-4 border-b" style={{ borderColor: 'rgba(255,255,255,0.06)', background: 'rgba(255,255,255,0.02)' }}>
              <span className="text-xl">{section.icon}</span>
              <h2 className="text-sm font-bold text-white/70">{section.title}</h2>
            </div>
            <div className="px-5">
              {section.faqs.map(f => <Faq key={f.q} q={f.q} a={f.a} />)}
            </div>
          </div>
        ))}
      </div>

      {/* Contact block */}
      <div className="mt-8 rounded-2xl border p-6" style={{ background: 'rgba(109,40,217,0.07)', borderColor: 'rgba(109,40,217,0.2)' }}>
        <div className="flex items-center gap-2 mb-4">
          <Zap className="w-4 h-4 text-purple-400" />
          <p className="text-sm font-bold text-white/70">Can't find your answer?</p>
        </div>
        <p className="text-xs text-white/45 mb-5 leading-relaxed">
          Your Cerebre account manager is your primary point of contact. You can also reach the support team directly.
        </p>
        <div className="grid sm:grid-cols-2 gap-3">
          {[
            { icon: MessageSquare, label: 'WhatsApp your account manager', sub: 'Fastest response — usually within 2 hours' },
            { icon: Mail, label: 'Email support', sub: 'support@cerebre.africa · 24hr response' },
          ].map(({ icon: Icon, label, sub }) => (
            <div key={label} className="flex items-start gap-3 p-3 rounded-xl" style={{ background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.07)' }}>
              <Icon className="w-4 h-4 text-purple-400 flex-shrink-0 mt-0.5" />
              <div>
                <p className="text-xs font-semibold text-white/70">{label}</p>
                <p className="text-[11px] mt-0.5" style={{ color: 'rgba(255,255,255,0.35)' }}>{sub}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
